// Generated by Wrangler by running `wrangler types`

interface Env {
  IDEMPOTENCY_KEYS: KVNamespace;
  APPLE_BUNDLE_ID: 'com.memorylocks.mlmobileapp';
  DB: D1Database;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
}
